server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.191.2:3306/aiomp?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  mail:
    host: smtp.163.com
    username: socks
    password: 123456
    properties:
      from: socks@163.com
  thymeleaf:
    cache: false
    prefix: classpath:views/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

http:
  encoding:
    charset:UTF-8

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.erick.aiomp.entity

